#pragma once

// Sea of Thieves (2) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "SoT_AthenaCheat_structs.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class AthenaCheat.AthenaCheatManager
// 0x00C0 (0x0138 - 0x0078)
class UAthenaCheatManager : public UCheatManager
{
public:
	class ACinematicCameraController*                  CinematicCameraController;                                // 0x0078(0x0008) (ZeroConstructor, IsPlainOldData)
	class UClass*                                      CinematicCameraControllerClass;                           // 0x0080(0x0008) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x28];                                      // 0x0088(0x0028) MISSED OFFSET
	TArray<struct FWorldMarkerDesc>                    CreatedWorldMarkers;                                      // 0x00B0(0x0010) (ZeroConstructor, Transient)
	class UGameEventSchedulerSettingsAsset*            DebugSchedulerSettings;                                   // 0x00C0(0x0008) (ZeroConstructor, Transient, IsPlainOldData)
	class AServerPerformanceReplicator*                ServerPerformanceReplicator;                              // 0x00C8(0x0008) (ZeroConstructor, Transient, IsPlainOldData)
	float                                              TeleportToDigsiteHeightOffset;                            // 0x00D0(0x0004) (Edit, ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData01[0x64];                                      // 0x00D4(0x0064) MISSED OFFSET

	static UClass* StaticClass()
	{
		static auto ptr = UObject::FindObject<UClass>(_xor_("Class AthenaCheat.AthenaCheatManager"));
		return ptr;
	}


	void WindTriggerChange(int ChangeInstantly);
	void WindSetVector(float X, float Y);
	void WindSetMagnitude(float Magnitude);
	void WindSetDirection(float X, float Y);
	void WindReloadParams();
	void WindPrintDirection();
	void WindEnableDebug();
	void WindDisableDebug();
	void WindAlignWithCamera();
	void Walk();
	void VomitWithType(const struct FName& VomitType, float Duration);
	void Vomit();
	void ValidateNPCCullingDistance();
	void UpdateInvasionAggressivePassiveTeleportOffsetDistance(const class FString& InDistance);
	void UpdateDisplayString(const class FString& Namespace, const class FString& Key, const class FString& SourceString);
	void UnlockTradeRouteSelectionForMyCrew();
	void UnlockTradeRouteSelectionForCrew(const struct FGuid& CrewId);
	void UnlockEntitlementCategory(const class FString& EntitlementMapToUnlock);
	void UnlockEntitlement(const class FString& EntitlementId);
	void UnlockAndEquipSkeletonCurse();
	void UnlockAndEquipItemFromEntitlement(const class FString& EntitlementId);
	void UnlockAndEquipGoldGhostCurse();
	void UnlockAndEquipGhostCurse();
	void UnlockAllTallTales();
	void UnlockAllSkeletonClothes();
	void UnlockAllEntitlements(int TrueFalse);
	void UnlockAllEmblemsAndAchievements();
	void UnBreakLeg();
	void TutorialAction(const class FString& ActionTypeString);
	void TriggerRewardNotification(struct FName* Identifier);
	void TriggerLosingCrewTale(const class FString& InCrewId);
	void TriggerLandmarkReaction(int ActionType);
	void TriggerFogManagerAtNearestIsland();
	void TriggerFactionBattleLosingBanner();
	void TriggerEmblemUnlockedMessage(const class FString& EmblemFriendlyName);
	void TriggerDebugAggressivePassiveInvasion(const class FString& InCrewId);
	void TriggerDebugAggressiveAggressiveInvasion(const class FString& InCrewId);
	void TriggerControllerConnectionChange(bool IsConnect, int UserId, int ControllerId);
	void TriggerContestMatchmakingMigration();
	void TriggerAIShipTimerBattle();
	void TriggerAIShipPassive();
	void TriggerAIShipEncounter();
	void TriggerAIShipAggressive();
	void TriggerAdvertiseGameEventsOnDemandAvailability();
	void ToggleVideprinter(const class FString& Id);
	void ToggleThirdPerson();
	void ToggleStoryRefresh();
	void ToggleStoryDisplayFilter(bool IsIncludeFilter, const class FString& Filter);
	void ToggleSeaClueLocationQueryDebugDisplay();
	void ToggleRetailDrawDebug();
	void ToggleNoClip();
	void ToggleNearestSuperheatedWater();
	void ToggleNearestLava();
	void ToggleMigrationPointOfInterestChecks(bool Enabled);
	void ToggleIslandSelectionDebugDisplay();
	void ToggleGlint();
	void ToggleFastShipControls();
	void ToggleFactionDebugDisplay();
	void ToggleDrowning();
	void ToggleDrawShipSpeed();
	void ToggleDrawAboveIslandBounds();
	void ToggleDisplayStories();
	void ToggleDisplayEmergentBattleBanners();
	void ToggleDisplayCannonAISpawnerZones();
	void ToggleDebugFlying();
	void ToggleDeathCamera();
	void ToggleDamageAllowedToPlayerShip();
	void ToggleCrewIdToBeBlockedFromBeingInvaded(const class FString& InCrewId);
	void ToggleContestScoreDebug();
	void ToggleCinematicCamera();
	void ToggleAudioReportingForVeryCloseAudio();
	void ToggleAudioReporting();
	void ToggleAttributeOverride();
	void ToggleAggressivePassiveTeleportUseEQS();
	void TestForceArchiveAsyncPoolCanaryCrash();
	void TestCrashDumpCreationOnRunnableThread();
	void TestCrashDumpCreationOnMainThread();
	void TeleportToShip();
	void TeleportToPlayerStart();
	void TeleportToNearestTreasureLocation();
	void TeleportToLocation(float LocationX, float LocationY, float LocationZ);
	void TeleportToHideout();
	void TeleportToDebugDestinationLocation(const class FString& ActorIdString, const class FString& DestinationId);
	void TeleportToAggressiveGhostShipEncounter();
	void TeleportShip(float X, float Y, float Z);
	void TeleportPlayerToSpireLocation(int SpireIndex);
	void TeleportPlayerToSafety();
	void TeleportPlayerToOffsetAndReturn(float OffsetX, float OffsetY, float OffsetZ, float ReturnTime);
	void TeleportPlayerToNearestActiveRiddleLandmark();
	void TeleportPlayerToMerchantCrateSpawnLocation();
	void TeleportPlayerToKraken();
	void TeleportPlayersCrewShipToPlayerLocation();
	void TeleportOutOfHideout();
	void TeleportCrewToShip(const class FString& CrewId);
	void TeleportCrewToSafeSpawnLocationFromRemoteActor(const class FString& ActorIdString, const class FString& CrewId);
	void TeleportCrewToSafeSpawnLocation(const class FString& CrewId);
	void TeleportCrewMemberToShip(const class FString& ActorIdString);
	void TeleportAllPlayersToShip();
	void TeleportAllPlayersToPlayerStart();
	void TeleportAllCrewsToShips();
	void TeleportAllCrewsToCrewSpawnLocations();
	void TeleportActorToTrackedActorType(const class FString& ActorIdString, int DestinationActorType);
	void TeleportActorToTeleportLocationActor(const class FString& ControllerActorIdString, const class FString& TeleportLocationActorIdString);
	void TeleportActorToPlayerBuriedDigSite(const class FString& ActorIdString);
	void TeleportActorToLocation(const class FString& ActorIdString, float LocationX, float LocationY, float LocationZ, float Yaw);
	void TeleportActorToIsland(const class FString& ActorIdString, const class FString& IslandName);
	void TeleportActorToDigSite(const class FString& ActorIdString, bool WasBuriedByPlayer);
	void TeleportActorToActorWithOffset(const class FString& ActorIdString, const class FString& DestinationActorIdString, float OffsetX, float OffsetY, float OffsetZ);
	void SwitchActiveStory(const class FString& StoryNameToRemove, const class FString& StoryNameToAdd, bool AddIfNonExistentStory);
	void SuperShovel();
	void SuperSailor();
	void StraightenAllTrinketsOnOwnShip();
	void StraightenAllTrinketsOnAllShips();
	void StoreWieldedItemInBootyStorageInCurrentIsland();
	void StoreWieldedItemInBootyStorage(const class FString& IslandName);
	void StoreShipLocation(float LocationX, float LocationY, float LocationZ, float Yaw);
	void StopShip();
	void StopPetHangout();
	void StopOverridingUGCState();
	void StopLocalSequences();
	void StopAllShips();
	void StopAllPetsHangout();
	void StockShip(const class FString& EntitlementAndAmountString);
	void StartVoyage(const class FString& SourceAssetName, bool Development);
	void StartTimedStatsCapture(float CaptureLengthInSeconds);
	void StartSicknessOnPlayer();
	void StartSelectedRomeVoyage(const class FString& RomeVoyageString);
	void StartNearestVolcano();
	void StartNearestGeysers();
	void StartNearestEarthquake();
	void StartInvasionMatchmaking();
	void StartGuildSessionAsNewCrew();
	void StartGuildSessionAsCrew();
	void StartDemoSession();
	void StartCargoRunFromNearestNPC(int NumOfCrates);
	void StartCaptaincySessionAsNewCrew();
	void StartAshenLordGeysers();
	void StartAllVolcanos();
	void StartAllCrewVoyages();
	void StarFieldMaskStartSkySpin();
	void SpireStreamOut(int SpireIndex);
	void SpireStreamIn(int SpireIndex);
	void SpinShip(float YawSpdInDegreesPerSecond);
	void SpawnWatercraftUnlimited(const class FString& WatercraftClassString);
	void SpawnWatercraft(const class FString& WatercraftClassString);
	void SpawnTreasureChestOfType(class FString* ChestTypeString);
	void SpawnTreasureArtifact(const class FString& TypeString);
	void SpawnTinySharkAtLocation(float X, float Y, float Z, int PartIndex);
	void SpawnTinySharkAtCurrentLocation(int ControllerParamIndex, int PartIndex);
	void SpawnStrongholdKeyFromGameEventType(const class FString& FortEventName);
	void SpawnStrongholdKey();
	void SpawnSmallShipAtIsland(const class FString& IslandName);
	void SpawnSmallShip(float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ, float SpawnYaw);
	void SpawnSkeletonAtNearestAISpawnPoint();
	void SpawnShipOfType(float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ, float SpawnYaw, const class FString& TypeString);
	void SpawnShipInFrontOfNearestAIInteractable(float XProportion, float YProportion, float Yaw, const class FString& TypeString);
	void SpawnShipFromDesc(const class FString& InShipDescAssetString, float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ, float SpawnYaw);
	void SpawnShipAtIsland(const class FString& IslandName);
	void SpawnShip(float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ, float SpawnYaw);
	void SpawnSeagull();
	void SpawnRandomSeagull();
	void SpawnOceanCrawlersOnShip();
	void SpawnNumberOfAI(const class FString& AIDescString, int NumToSpawn);
	void SpawnNightmareAggressiveGhostShipEncountersRandom();
	void SpawnNightmareAggressiveGhostShipEncountersNearToPlayer();
	void SpawnMultipleTreasureChestsOfType(int Num, class FString* ChestTypeString);
	void SpawnMessageInABottle(const class FString& MessageInABottleTypeString);
	void SpawnMermaid();
	void SpawnMerchantFauna(const class FString& FaunaTypeString);
	void SpawnMerchantCrate(const class FString& MerchantCrateTypeString);
	void SpawnMerchantCargo(const class FString& MerchantCargoTypeString);
	void SpawnKrakenAtCurrentLocationWithNumTentacles(uint32_t NumTentacles);
	void SpawnKrakenAtCurrentLocation();
	void SpawnItemOnFloor(const class FString& ItemString);
	void SpawnItemInHand(const class FString& ItemString);
	void SpawnGoldMound(const class FString& GoldMoundTypeString);
	void SpawnGeyserAtPlayerLocationWithDormancy(float Dormancy);
	void SpawnGeyserAtPlayerLocation();
	void SpawnGeyserAtLocation(float LocationX, float LocationY, float LocationZ, float Dormancy);
	void SpawnFogAtPlayerPosition();
	void SpawnFishAtPlayerLocation(const class FString& InBaitType);
	void SpawnFirework(const class FString& FireworkItemString);
	void SpawnCursedCannonball(const class FString& CannonballTypeString);
	void SpawnContextualPrompt(const class FString& PromptAccessKey);
	void SpawnCollectorsChestOfType(class FString* ChestTypeString, class FString* RewardId);
	void SpawnCargoRunCrate(const class FString& SpawnCargoRunCrateString);
	void SpawnCabinDoorInFrontOfPlayer(float Distance);
	void SpawnBountyReward(const class FString& BountyTypeString);
	void SpawnBootyPickupPoint();
	void SpawnBarrelGroup(bool ForcedCloseSpawn);
	void SpawnAThousandTreasureChests();
	void SpawnAndEquipDebugWieldable(const class FString& DebugWieldableTypeString);
	void SpawnAllBooty(int InNumOfEachToSpawn);
	void SpawnAINoTrigger(const class FString& AIDescString);
	void SpawnAIEncounter(const class FString& AIEncounterString);
	void SpawnAIAtNearestAISpawnPoint(const class FString& AIDescString);
	void SpawnAIAtLocationDelayed(const class FString& AIDescString, float LocationX, float LocationY, float LocationZ, float Yaw, float Delay);
	void SpawnAIAtCurrentLocationDelayed(const class FString& AIDescString, float Delay);
	void SpawnAI(const class FString& AIDescString);
	void SpawnAggressiveGhostShipEncounterSpireTheHellishMermaid();
	void SpawnAggressiveGhostShipEncounterSpireFriendlyFormation();
	void SpawnAggressiveGhostShipEncounterSpireEnemyFormation();
	void SpawnAggressiveGhostShipEncounterSpire();
	void SpawnAggressiveGhostShipEncounter();
	void SmoulderClosestShipFire();
	void SmoulderAllShipFires();
	void SlowMotionOverride(bool InValue);
	void SkipToEndOfOnboarding();
	void SinkShipWithKeelOverIndex(int KeelOverConfigIndex);
	void SinkShipByActorId(const class FString& ShipActorIdString);
	void SinkShip();
	void SinkClosestItemProxy();
	void SinkAllBarrels();
	void SinkAllAIShips();
	void SingleStickSwap();
	void SingleStickRight();
	void SingleStickOff();
	void SingleStickLeft();
	void SimulateTunnelFailure();
	void SimulatePetReactRequest(const class FString& Id);
	void SimulatePetReactCancellation(const class FString& Id);
	void SignalActiveGlobalVoyageDelaySteps();
	void ShowTaleDebug_WithVariables();
	void ShowTaleDebug();
	void ShowShipMilestoneToast(const class FString& MilestoneGuid, const class FString& MilestoneAlignment, uint64_t MilestoneLevel, const class FString& ShipName);
	void ShowRandomCrewMemberGamerCard();
	void ShowPlayerMilestoneToast(const class FString& MilestoneGuid, const class FString& MilestoneAlignment, uint64_t MilestoneLevel);
	void ShowEmissaryVoteIndicators();
	void ShowAllWelds();
	void ShowAllianceStatus(const class FString& CrewId);
	void ShipwrecksSpawnOne(float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ);
	void ShipwrecksSpawnCustom(float SpawnLocationX, float SpawnLocationY, float SpawnLocationZ, const class FString& WreckAsset);
	void ShipwrecksRemoveCustom();
	void ShipwrecksRegen();
	void ShipUpdateMassProperies();
	void ShipSurface();
	void ShipDive();
	void SetWheelAngle(float Angle);
	void SetWeaponsLockedOut(bool WeaponsLockedOut);
	void SetWaveFlag(int InFlag);
	void SetWaterWaveParams(float Amplitude, float WaveLength, float PropagationSpeed);
	void SetVoiceChatEndpointXAudio2();
	void SetVoiceChatEndpointWwise();
	void SetUnattenuatedChatMixingMethodToUseWwise();
	void SetUnattenuatedChatMixingMethodToUsePlatform();
	void SetTrinketsEnabled(bool InTrinketsEnabled);
	void SetTrinketNudgeChanceMaxOnAllShips();
	void SetTinySharkToOneHealth();
	void SetTimeScalar(float TimeScalar);
	void SetTimeHoursAndMinutes(int Hours, int Minutes);
	void SetTime(int Hours);
	void SetTaleSelectorSeed(int Seed);
	void SetShroudbreakerActive(bool bActive);
	void SetShipYaw(float Yaw);
	void SetShipWheelFullyRepaired();
	void SetShipWheelFullyDamaged();
	void SetShipRoll(float Roll);
	void SetShipName(const class FString& InShipName);
	void SetShipFullyDamaged();
	void SetShipCapstanFullyRepaired();
	void SetShipCapstanFullyDamaged();
	void SetShipCanSailForAGuild(bool InCanSailForAGuild);
	void SetShipBuoyancyBlend(float UnaryBlend);
	void SetSeaFortAllEnemiesDeadOnAlignmentFlag(int InFort, bool IsDead);
	void SetSeaFortAlignment(int InFort, int InAlignment);
	void SetSailLoweredProportions(float Proportion);
	void SetSailAngles(float Angle);
	void SetRitualTableRequiredPlayersOverride(int RequiredPlayerCount);
	void SetPreventLeakingOnAllShips();
	void SetPreventLeakingOnAllDamageZones(bool PreventLeaking);
	void SetPlayerVisibleToAI();
	void SetPlayerMaxTicks(int InMaxTicksPerFrame);
	void SetPlayerInvisibleToAI();
	void SetPlayerInert(bool IsInert);
	void SetPlayerGuildSlotsAreFull(bool InSlotsAreFull);
	void SetPlayerCanInviteToGuild(bool InCanInvite);
	void SetPhotoMode(bool Enabled);
	void SetPetMovementTimeWindow(float TimeWindow);
	void SetOverridenUGCState(bool InOverridenUGCState);
	void SetNonCrewChatSpatialisation(bool Enabled);
	void SetMaxNumOfSpawnedAI(int MaxNumOfSpawnedActors);
	void SetMaxMovingPetsOnShips(int MaxMovingPets);
	void SetMaxMovingPetsOnServer(int MaxMovingPets);
	void SetMaxMovingPetsOnLand(int MaxMovingPets);
	void SetMastsFullyRepaired();
	void SetMastsFullyDamaged();
	void SetKnockbackDisabled(bool Disabled);
	void SetIsTinSession(bool InIsCaptainedSession);
	void SetIsShipCustomizationTinOnly(bool InIsShipCustomizationCaptainOnly);
	void SetIsCaptain(bool InIsCaptain);
	void SetIdleDisconnectEnabled(bool Enabled);
	void SetHealthInfoReplicateOverride(bool bActive);
	void SetGuildName(const class FString& InStringGuildName);
	void SetGuildMotto(const class FString& InStringGuildMotto);
	void SetGuildLevelToRequiredLevelToUnlockGuildEmissary();
	void SetGuildIsFull(const class FString& InStringGuildId, bool InGuildIsFull);
	void SetGuildIcon(const class FString& InStringGuildIcon);
	void SetGrogSecondary(bool InValue);
	void SetGodMode(bool GodModeOn);
	void SetGlitterbeardRequiredPlayersOverride(int RequiredPlayerCount);
	void SetFOV(float InNewFOV);
	void SetForceLocalPlayerMoveForwardFlipDistance(float FlipDistance);
	void SetFlameOfFateColour(int InFlameOfFateType);
	void SetFactionStreak(int InStreak);
	void SetDebugItemSource(const class FString& Source);
	void SetDebugHealthStage(int InStage);
	void SetDebugCameraUseProjectileCollisionChannel(bool bUseProjectileChannel);
	void SetDeathPenaltyRespawnTimer(float InSpawnTimer);
	void SetDeathPenaltyCrewBasedRespawnTimes(float CrewOfOne, float CrewOfTwo, float CrewOfThree, float CrewOfFour);
	void SetDamageAllowedToPlayerShip(bool InAllowDamage);
	void SetCVarOnTheServer(const class FString& CVarName, int Value);
	void SetCutsceneResponseCoordinatorDebug(bool Value);
	void SetCurrentCulture(const class FString& Culture);
	void SetCrewSkill(const class FString& TargetCrew, int Skill);
	void SetCrestTextVisibility(bool InShouldShowText);
	void SetCoordinatedKrakenPhaseAsset(int AssetIndex);
	void SetCoordinatedKrakenCurrentPhaseAssetInactive();
	void SetCoordinatedKrakenCurrentPhaseAssetActive();
	void SetCapstanPosition(float Position);
	void SetAxisBinding(const class FString& InBindingName, const class FString& InKeyName);
	void SetAllShipsSailsAngle(float Angle);
	void SetAllShipsSailLoweredProportions(float Proportion);
	void SetAllSeaFortsAlignment(int InAlignment);
	void SetAllCapstanPositions(float Position);
	void SetAllAIOverrideCannonShotHitChance(float HitChance);
	void SetAITeamAttitude(const class FString& TeamAString, const class FString& TeamBString, const class FString& AttitudeString);
	void SetAIExclusiveAbility(const class FString& AIAbilityString);
	void SetAIAbilityTimeMultiplier(const class FString& AIAbilityString, float IntervalCooldownMultiplier, float ActivationCooldownMultiplier);
	void SetAbilityAlwaysOn(const class FString& AIAbilityString);
	void SendUpdateVoyageProgressEvent();
	void SendStatEvent(uint32_t StatId, uint64_t StatValue);
	void SendRewardRequestEvent(const class FString& CompanyNameAndRewardIdSeparatedByColon);
	void SendResetReaperLevelEvent();
	void SendPlayerToFerrySinBin();
	void ScuttleShip(bool InShouldSendCrewToLosingTunnel);
	void ScreenFadeStart();
	void ScreenFadeEnd();
	void SchedulerToggleUseRemoteService();
	void SchedulerToggleDebugDraw();
	void SchedulerSkipToNext();
	void SchedulerInitTinyShark();
	void SchedulerInitSkellyFort();
	void SchedulerInitOceanCrawlersOnShip();
	void SchedulerInitLegendarySkellyFort();
	void SchedulerInitKraken();
	void SchedulerInitDefault();
	void SchedulerInitCompetitiveVoyage();
	void SchedulerInitAshenLord();
	void SchedulerInitAIShipPassive();
	void SchedulerInitAIShipBattle();
	void SchedulerInitAIShipAggro();
	void SchedulerInitAggroGhostShip();
	void SchedulerAdvance(float Time);
	void SaveMyShip();
	void SailShip();
	void SailAllShips();
	void RewindPhysicsSceneBy(float SecondsToRewindBy);
	void RewardPlayer(const class FString& RewardId);
	void ReviveLocalPlayerInstantly();
	void ReviveLocalPlayerAccordingToReviveTime();
	void RetrieveItemsFromBootyStorageInCurrentIsland();
	void RetrieveItemsFromBootyStorage(const class FString& IslandName);
	void ResurfaceShipByActorId(const class FString& ShipActorIdString);
	void RestoreAndRestockShipAndPlayer();
	void RestockIslandBarrels();
	void RestockAllReplenishables();
	void RespawnAllIslandItemSpawners();
	void ResetTinySharkSpawnTimerWithTime(float Timer);
	void ResetTinySharkSpawnTimer();
	void ResetTaleSelectorSeed();
	void ResetStats();
	void ResetRitualTable();
	void ResetRepairedShipDamage();
	void ResetNearestVault();
	void ResetNearestSeaFort();
	void ResetNearestEventRoom();
	void ResetMouseDelta();
	void ResetMaxNumOfSpawnedAI();
	void ResetMaxMovingPetsOnServerToDefault();
	void ResetLeaveFactionCooldown();
	void ResetInvasionMatchmakingCooldown();
	void ResetInitialMatchmakingCooldown();
	void ResetGlitterbeardTree();
	void ResetDemoSession(bool StartNewSession);
	void ResetCrewsJoinedGameEventOnDemand(const class FString& InGameEventType);
	void ResetAllShipDamage();
	void ResetAllOverrideCannonShotHitChance();
	void ResetAllMechanisms();
	void ResetAITeamAttitudes();
	void ResetAIExclusiveAbilities();
	void ResetActiveStories();
	void ResetAbilityAlwaysOn();
	void RequestSmallPassiveAIShip();
	void RequestSmallAggressiveAIShip();
	void RequestMysteriousNotesForPlayer();
	void RequestLargePassiveAIShip();
	void RequestLargeAggressiveAIShip();
	void RequestDiveToAdventure();
	void RequestCaptainedSessionCrewData();
	void ReplenishShipWithDebugSpawner();
	void ReplenishShip();
	void ReplaceShipWithSmallShip(const class FString& ShipActorIdConsoleString);
	void RepairShipAndClearInternalWater();
	void RepairAndClearInternalWaterOnAllShips();
	void RenameTreasure(const class FString& InVendorName);
	void RemoveVoyageFromShip(const class FString& SourceAssetName);
	void RemoveSkeletonCurseEntitlement();
	void RemovePetsFromAllPlayers();
	void RemovePetFromPlayer();
	void RemoveLostShipmentsDebugging();
	void RemoveLastAddedVoyageFromShip();
	void RemoveItemInSlot(int SlotIndex);
	void RemoveGhostCurseEntitlement();
	void RemoveDebugPetSpawners();
	void RemoveDebugHealthStage();
	void RemoveAllSkeletonClothing();
	void RemoveAllFog();
	void RemoveAISpawnContext(const class FString& ContextName);
	void RemoveActiveStory(const class FString& StoryName);
	void RefreshActiveStories();
	void RebuildPirateFromSeed(int Seed);
	void ReallyScrambleMyGamertag();
	void QueryShipStocks();
	void PuzzleManager_ResetAllPuzzlesOnClosestManager();
	void Puzzle_UnlockLockByIndex(const class FString& TargetActor, int LockIndex);
	void Puzzle_UnlockLock(const class FString& TargetActor, const struct FGuid& Guid);
	void Puzzle_UnlockAllLocks(const class FString& TargetActor);
	void Puzzle_ResetUnlock(const class FString& TargetActor);
	void Puzzle_ActivateAllLocks(const class FString& TargetActor);
	void PushShip(float FwdSpdInMetersPerSecond);
	void PullLatestEmblemProgress();
	void ProposeVoyageFromShip(const class FString& SourceAssetName);
	void ProposeLastAddedVoyageFromShip();
	void ProceedToNextContestState();
	void PrintTime();
	void PrintNPCs();
	void PrintAllNetworkActors();
	void PrintAISpawners();
	void PrintAISpawnContexts();
	void PrimeRitualTable();
	void PreventTunnelMatchmakingForCrew();
	void PreventShipMotion();
	void PlayWorldSequence(const class FString& InReference);
	void PlayLocalSequences();
	void PlayerAnimationOverride(const struct FName& Name);
	void OverrideShipPartFromCatalogue(const class FString& InShipActorIdConsoleString, int InCataloguePartIndex, int InCataloguePartCustomisationIndex);
	void OpenSkeletonFortDoor();
	void NudgeAllTrinketsOnOwnShip();
	void NudgeAllTrinketsOnAllShips();
	void MoveStormToPlayer();
	void MoveStormToLocation(float LocationX, float LocationY);
	void MoveStormToIsland(const class FString& IslandNameString);
	void MessageBoxOnGraphicsThreadTest();
	void MakeSharksBrainDead();
	void MakeDebugPetSpawner();
	void LogShipHierarchy();
	void LogServerShipHierarchy();
	void LogAITeamAttitudes();
	void LockTradeRouteSelectionToSpecificRouteForMyCrew(const class FString& RouteReferencePath);
	void LockTradeRouteSelectionToSpecificRouteForCrew(const struct FGuid& CrewId, const class FString& RouteReferencePath);
	void LocallyUnBreakLeg();
	void LocallyDisableTutorial();
	void LoadMyShip();
	void LightLocalBraziers();
	void LightBraziersInRadius(float Radius);
	void LeaveFaction();
	void LeaveAlliance(const class FString& CrewId);
	void LayerSpawn(const class FString& LayerAsset);
	void LayerClearAll();
	void LayerClear(const class FString& LayerAsset);
	void LaunchPlayer(float Velocity, float Angle);
	void KrakenSetTentaclesToOneHealth();
	void KrakenAnimatedTentacleThrowPlayer();
	void KrakenAnimatedTentacleTakeDamage(float Damage);
	void KrakenAnimatedTentacleSwallowPlayer();
	void KrakenAnimatedTentacleSuckPlayer();
	void KrakenAnimatedTentaclePowerSlamPlayer();
	void KrakenAnimatedTentacleKill();
	void KrakenAnimatedTentacleIngestPlayer();
	void KrakenAnimatedTentacleDropPlayer();
	void KrakenAnimatedTentacleDespawn();
	void KrakenAnimatedTentacleDefeat();
	void KrakenAnimatedTentacleChangePlayerHoldState(const class FString& HoldState);
	void KindleClosestShip();
	void KindleAllShipFires();
	void KillPlayer();
	void KillCrew(const class FString& CrewId);
	void KillAllSkeletons();
	void KillAllPlayers();
	void KillAllOtherPlayers();
	void KillAllOtherPlayerCharacters();
	void KillAllDebugAISpawners();
	void KillAllCrews();
	void KillAllAI();
	void KillAllAggressiveGhostShips();
	void KillAllAggressiveGhostShipEncounters();
	void JoinFaction(const class FString& FactionName);
	void JoinAlliance(const class FString& OfferingCrew, const class FString& AcceptingCrew);
	void IPGOverride(const struct FName& BodyShape, float Distance);
	void IPGLoadWithoutClothing(const class FString& ActorIdString, const class FString& path);
	void IPGLoadWithClothing(const class FString& ActorIdString, const class FString& path);
	void IPGLoad(const class FString& path);
	void InvincibleEverything();
	void InterruptSicknessOnPlayer();
	void InfiniteGunAmmo(bool Enabled);
	void IncrementTime(int Hours, int Minutes);
	void IncrementFactionStreak();
	void IncrementDebugHealthStage();
	void IncreaseEmissaryCount(int Amount);
	void IgniteShipAtPlayerLocation();
	void IgniteLocalPlayer();
	void IgniteClosestShip();
	void IgniteAllShipFires();
	void HuntersCryForceRescueSuccess();
	void HuntersCryForceRescueFail();
	void HuntersCryDisableTimedFail();
	void HitRegSnapshotsToggleOnScreenStatus();
	void HitRegSnapshotsSetShowPreCorrectedCapsules(bool ShowPreCorrectedCapsules, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetShowFullRewindData(bool ShowFullRewindData, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetDisplaySnapshots(bool ShowSnapshots, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetDisplayServerData(bool ShowServerData, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetDisplayDetailedExplanations(bool ShowExplanations, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetDisplayAttackingClientData(bool ShowClientData, bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsSetDisagreementModeToComponents();
	void HitRegSnapshotsSetDisagreementModeToAllShots();
	void HitRegSnapshotsSetDisagreementModeToActors();
	void HitRegSnapshotsResetVisibilitySettingsToDefault(bool AffectAllSnapshots, bool LocalClientOnly);
	void HitRegSnapshotsEnableSystem();
	void HitRegSnapshotsDisableSystem();
	void HitRegSnapshotsDestroyAll();
	void HitRegSetPlayerProjectilesHitScan(bool Enabled);
	void HideTaleDebug();
	void HideEmissaryVoteIndicators();
	void HealthSet(float Value);
	void HealthReset();
	void HealthRegenResetToEmpty();
	void HealthRegenAdd(float Value);
	void HealthContinuousStopWithTestReason();
	void HealthContinuousStopWithReason(const class FString& Reason);
	void HealthContinuousStartWithTestReason(float Value);
	void HealthContinuousStartWithReason(float Value, const class FString& Reason);
	void HealthAdjust(float Amount);
	void HandInMegalodonSoulToRitualTable(int SoulType);
	void God();
	void GetSourceStringHash(const class FString& SourceString);
	void GameEventOnDemandAvailabilityServiceToggleDebugDraw();
	void ForceStopAllPetsDanger();
	void ForceStartAllPetsDangerWithChangingThreatLocation(const class FString& ResponseType, float UpdateThreatLocationTime);
	void ForceStartAllPetsDanger(const class FString& ResponseType);
	void ForceSkipTallTaleSteps_WaitAndCutscenes();
	void ForceRequestCampaignsFromServices();
	void ForcePetHangout(const struct FName& HangoutName, int PositionIndex);
	void ForceOpenShop();
	void ForceNPCOnSurfaceToMove(bool FastMove, bool KeepCurrentLocation);
	void ForceNPCOnSurfaceLocation(int LoctationIndex, int LoctationPointIndex);
	void ForceNPCOnShipIsCurrentlyInDanger(bool IsCurrentlyInDanger);
	void ForceLocalPlayerMoveForward(float ScaleValue);
	void ForceLocalPlayerMeleeCombo(float Interval);
	void ForceLocalPlayerMeleeAttack(float Frequency);
	void ForceGarbageCollect();
	void ForceEmoteWithEmoteProp(const struct FName& EmoteIdentifier, const class FString& EmotePropAssetLocation);
	void ForceEmoteWithDescriptionAndEmoteProp(const struct FName& EmoteIdentifier, const class FString& DisplayName, const class FString& AudioDescription, const class FString& EmotePropAssetLocation);
	void ForceEmoteWithDescription(const struct FName& EmoteIdentifier, const class FString& DisplayName, const class FString& AudioDescription);
	void ForceEmote(const struct FName& EmoteIdentifier);
	void ForceCloseShop();
	void ForceAllPetsDangerWithNoiseEventWithChangingThreatLocation(const class FString& ResponseType, float UpdateThreatLocationTime);
	void ForceAllPetsDangerWithNoiseEvent(const class FString& ResponseType);
	void ForceAggressiveGhostShipStartSinkingAnimation();
	void ForceAggressiveGhostShipStartDisappearAnimation();
	void ForceAggressiveGhostShipStartAppearAnimation();
	void ForceAggressiveGhostShipPortalJump();
	void Fly();
	void FloodShipWithKeelOverIndex(float NormalisedWaterAmount, int KeelOverConfigIndex);
	void FloodShip(float NormalisedWaterAmount);
	void FireStartedCaptainedSessionEvent();
	void FireSeasonRewardEarnedMessage(int InNumSeason, int InRewardsLevel, bool InMultipleRewards);
	void FireSeasonGoalProgressionMessage(int InNumSeason, int InPreviousProgress, int InCurrentProgress, int InCompletionTreshold, int InGoalType, const class FString& InGoalCategory);
	void FireSeasonGoalCompletionMessage(int InNumSeason, int InGoalType, const class FString& InGoalCategory);
	void FireOnlineSessionMemberLostEventForMyself();
	void FireLevelCompletionMessage(int InNumSeason, int InLevel, int InTimeSpentInLevel, int InTier, int InTimeSpentInTier, bool InTierCompleted, bool InSeasonCompleted);
	void FireEndedGuildSessionEvent();
	void FireCreatorCrewSignedUpStat();
	void FireCreatorCrewMinutesViewedStat(int InNumMinutes);
	void FireCreatorCrewMinutesStreamedStat(int InNumMinutes);
	void FireCreatorCrewCurrentViewersStat(int InNumViewers);
	void FindOrAddDisplayString(const class FString& Namespace, const class FString& Key, const class FString& SourceString);
	void FindDisplayString(const class FString& Namespace, const class FString& Key);
	void FillNearestShipWithTrinkets();
	void FakeMigrateBountyQuests();
	void ExitedStormShipEvent();
	void EquipPirateTitle(const class FString& PirateTitleType);
	void EquipCompassInLoadout();
	void EnteredStormShipEvent();
	void EndDemoSession();
	void EndCurrentCaptainedSession();
	void EnableVoiceChatMeteringForOutgoingSignals(bool Enabled);
	void EnableVoiceChatMeteringForIncomingSignals(bool Enabled);
	void EnableStoryServiceCheat();
	void EnableStormEffects(unsigned char LockReason);
	void EnableSelectShipwreckLocationFromValidCandidatesDebugDisplay(int TrueFalse);
	void EnableNTP(bool Enable);
	void EnableMermaidSpawning(int Enable);
	void EnableMermaidDeletion(int Enable);
	void EnableHeadphoneMixing(bool Enabled);
	void EnableFactionDebug();
	void EnableEmergentSirenSpawning();
	void EnableEmergentSharkSpawning();
	void EnableConsoleLogging();
	void EnableCinematicCamera();
	void EnableBeaconOnAllMermaids(int Enable);
	void EnableAllEmergentWaterSpawning();
	void EnableAIBehaviour();
	void EmptyNearestShipOfTrinkets();
	void DrawVideprinter(const class FString& Id, bool Active);
	void DrawTreasureDebug(int Enabled);
	void DrawTemporaryLandmarkDebug(bool Enabled);
	void DrawNearbyAISpawnPointsRanged(float Range);
	void DrawNearbyAISpawnPoints();
	void DownPlayer();
	void DownAllPlayers();
	void DownAllOtherPlayers();
	void DownAllOtherPlayerCharacters();
	void DouseClosestShip();
	void DouseAllShipFires();
	void DiveShipByActorId(const class FString& ShipActorIdString);
	void DisplaySpireLocationsDebug(int Enabled);
	void DisplaySingleEmblemProgress(const class FString& StatName);
	void DisplayServersideHitsAtPlayerPosWithDefaults();
	void DisplayServersideHitsAtPlayerPos(uint32_t NumSamplesPerDimension, float DistanceBetweenSamples, float TestHeight);
	void DisplayServerFPS();
	void DisplayNonVagueNonUniqueLandmarksForIsland(bool Enabled);
	void DisplayLoadingScreenTeleport();
	void DisplayLoadingScreenBoot();
	void DisplayLoadingScreenAdventure();
	void DisplayLandmarkValidTreasureLocationsForPlayer();
	void DisplayLandmarkRegions();
	void DisplayLandmarkNames();
	void DisplayFallDamageDebug(int Enable);
	void DisplayDrunkenness(bool Flag);
	void DismissAllPickupPoints();
	void DisableStormEffects(unsigned char LockReason);
	void DisableEmergentSirenSpawning();
	void DisableEmergentSharkSpawning();
	void DisableConsoleLogging();
	void DisableCinematicCamera();
	void DisableAllEmergentWaterSpawning();
	void DisableAIBehaviour();
	void DisableAIAbilities();
	void DioramaStartNearest(const class FString& Spawner, const class FString& DioramaDesc);
	void DioramaStart(const class FString& ActorName, const class FString& Spawner, const class FString& DioramaDesc);
	void DioramaKillAllDebug();
	void DestroyShip(const class FString& ShipActorIdConsoleString);
	void DestroyNearestDebugReapersChestMarker();
	void DestroyMyShip();
	void DestroyKraken();
	void DestroyAllTreasureChests();
	void DestroyAllTinySharks();
	void DestroyAllSirenStatues();
	void DestroyAllShips();
	void DespawnNumberOfAI(const class FString& AITypeString, int NumToDespawn);
	void DespawnFirstAI();
	void DespawnAllAggressiveGhostShips();
	void DespawnAI(const class FString& AITypeString);
	void DeleteVoyageHistory();
	void DeleteAllMermaids();
	void DecrementFactionStreak();
	void DecrementDebugHealthStage();
	void DebugLoadRowboat(const class FString& WatercraftEntitlement, const class FString& LiveryEntitlement);
	void DebugIslandDelta();
	void DeactivateSkellyFort(const class FString& FortName);
	void DeactivateEmissaryFlagCompany();
	void DeactivateDeathEffect();
	void DamageShipFromRemoteActor(const class FString& ActorIdString, float Strength, float CameraLocationX, float CameraLocationY, float CameraLocationZ, float CameraForwardDirectionX, float CameraForwardDirectionY, float CameraForwardDirectionZ);
	void DamageShip(float Strength);
	void DamagePlayerFromRemoteActor(const class FString& ActorIdString, float Strength, float CameraLocationX, float CameraLocationY, float CameraLocationZ, float CameraForwardDirectionX, float CameraForwardDirectionY, float CameraForwardDirectionZ);
	void DamagePlayer(float Strength);
	void CustomiseNearestRowboat(const class FString& LiveryDescStringRef);
	void CureAllAilings();
	void CreateDebugReapersChestMarkerAtPlayerLocation();
	void CreateDebugAISpawnerAt(const class FString& SpawnerAssetName, const class FString& LocationActorName);
	void CreateDebugAISpawner(const class FString& SpawnerAssetName);
	void CreateCaptainsLogForCrew();
	void CoordinatedKrakenToggleAI();
	void CoordinatedKrakenRequestAction(const class FString& ActionName);
	void CoordinatedKrakenEnableDebugging(int Enable);
	void ContextualPromptCountersToggleDebugDraw();
	void CompleteVoyage();
	void CompleteCurrentChecklistMap();
	void CompleteAllActivePuzzleVaults();
	void CompleteActiveQuests();
	void CloseSkeletonFortDoor();
	void CloseLoadingScreen();
	void ClearWorldSequences();
	void ClearVoiceChatMeters();
	void ClearStoryDisplayFilter();
	void ClearSlowMotionOverride();
	void ClearShipVoyages();
	void ClearRitualTableRequiredPlayersOverride();
	void ClearGrogSecondary();
	void ClearGlitterbeardRequiredPlayersOverride();
	void ClearDebugStormLocation();
	void ClearCampaignOverrides();
	void ClearAxisBinding(const class FString& InBindingName);
	void ClearAIAbilityTimeMultipliers();
	void ClearAdventureOnDemandCrewDiveCooldown();
	void CheckLandmarkValidTreasureLocationsAtPlayerPos();
	void CheckLandmarkRelativeToIslandCalculation();
	void CapsizeShip();
	void CancelVoyage();
	void CancelTale();
	void CancelLeaveFactionCooldown();
	void CancelInvasionMatchmakingCooldown();
	void CancelInitialMatchmakingCooldown();
	void CancelEmergentVoyages();
	void CancelDebugInvasion(const class FString& InCrewId);
	void CancelCurrentMatchmakingCooldownForAllCrews();
	void CancelAllDebugInvasions();
	void CancelAllCrewVoyages();
	void CancelActiveAIShipEncounters();
	void BuryNearestBuriable();
	void BuryItem(const class FString& NameOfItemToBury);
	void BreakLeg();
	void BlockMigrationForPlayer(bool Enabled);
	void ApplyStatusToPlayer(const class FString& StatusIdentifier, float Duration);
	void ApplyDamageToAllDamageZones(float Damage);
	void ApplyCursedCannonballStatusToShip(const class FString& CannonballTypeString);
	void ApplyCursedCannonballStatusToPlayer(const class FString& CannonballTypeString);
	void AllowTunnelMatchmakingForCrew();
	void AllowTeleportWithItems(bool CanTeleport);
	void AllowShipMotion();
	void AllocatePortalToTunnelOfTheDamned(const class FString& TunnelDescAssetPath);
	void AllJoinAlliance();
	void AIPlayerShip();
	void AggressiveGhostShipRebuildSpline();
	void AdjustGhostShader(bool Enabled, float InStartingAmount, float InTargetAmount, float InVengeanceStartingAmount, float InVengeanceTargetAmount, float InDelayBeforeStart, float InBlendDuration);
	void AddVoyageToShip(const class FString& SourceAssetName);
	void AddTradeRouteNPCHintDialogClueMarkToMapAtCurrentLocation();
	void AddTradeRouteMessageInABottleClueMarkToMapAtCurrentLocation();
	void AddTradeRouteClueMarkToMapAtCurrentLocation();
	void AddTornMapPiece();
	void AddShipToCrew(const class FString& ActorIdString, const class FString& CrewId);
	void AddRandomPetForAllPlayers();
	void AddPlayerToCrew(const class FString& ActorIdString, const class FString& CrewId);
	void AddPetForPlayer(int PetTypeIndex, int PetPartIndex);
	void AddPetForAllPlayers(int PetTypeIndex, int PetPartIndex);
	void AddNoParameterEventLogEntryToCaptainsLog();
	void AddMysteriousNote(const class FString& NoteType, const class FString& NoteTitle, const class FString& NoteBody, const class FString& CompletionStrings);
	void AddLongEventLogEntryToCaptainsLog();
	void AddInvasionBattleBounds();
	void AddInactiveCampaignOverride(const class FString& CampaignName);
	void AddDrunkenness(int DrunkennessType, float DrunkennessChange);
	void AddAllKnownStories();
	void AddAISpawnContext(const class FString& ContextName);
	void AddActiveStory(const class FString& StoryName, bool AddIfNonExistentStory);
	void AddActiveCampaignOverride(const class FString& CampaignName);
	void ActivateSkellyFort(const class FString& FortEventName, const class FString& FortName);
	void ActivateEmissaryFlagCompany(const class FString& CompanyId);
	void ActivateDebugTeleportationDestinationService();
};


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
